---
# rhcos_json fact already set in 23_rhcos_image_paths.yaml

- name: Set cache_url to cache host, if present
  set_fact:
    cache_url: "http://{{ groups['cache'][0] }}/"
  when: (cache_url is not defined or cache_url == '') and (groups['cache'] | length) == 1

# Since we are using the cache, we want the RHCOS_PATH for the RHCOS image
# to point to whatever we have in our cache_url
- name: Override existing rhcos_path variable
  set_fact:
    rhcos_path: "{{ cache_url }}"

- name: Inject RHCOS image cache URLs into install-config.yaml (4.4+ only)
  blockinfile:
    path: "{{ item }}"
    insertafter: "dnsVIP:"
    block: |4
            bootstrapOSImage: "{{ rhcos_path }}{{ rhcos_qemu_uri }}?sha256={{ rhcos_qemu_sha256 }}"
            clusterOSImage: "{{ rhcos_path }}{{ rhcos_uri }}?sha256={{ rhcos_sha256 }}"
  with_items:
    - "{{ dir }}/install-config.yaml"
    - "{{ dir }}/install-config.yaml.bkup"
  #when: (release_version[0]|int > 4) or (release_version[2]|int > 3)
  